version: "2"

linters:
  # enabled in addition to the v2 defaults
  enable:
    - gosec
  exclusions:
    # Excluding configuration per-path, per-linter, per-text and per-source
    rules:
      # Exclude some linters from running on tests files.
      - path: _test\.go
        linters:
          - gosec
