// Code generated by "stringer -type=EndpointVersion"; DO NOT EDIT.

package defs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UnknownTrust-0]
	_ = x[Trust2005-1]
	_ = x[Trust13-2]
}

const _EndpointVersion_name = "UnknownTrustTrust2005Trust13"

var _EndpointVersion_index = [...]uint8{0, 12, 21, 28}

func (i EndpointVersion) String() string {
	if i < 0 || i >= EndpointVersion(len(_EndpointVersion_index)-1) {
		return "EndpointVersion(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EndpointVersion_name[_EndpointVersion_index[i]:_EndpointVersion_index[i+1]]
}
