// Code generated by "stringer -type=RefreshTokenReqType"; DO NOT EDIT.

package requests

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RefreshTokenUnknown-0]
	_ = x[RefreshTokenPublic-1]
	_ = x[RefreshTokenConfidential-2]
}

const _RefreshTokenReqType_name = "RefreshTokenUnknownRefreshTokenPublicRefreshTokenConfidential"

var _RefreshTokenReqType_index = [...]uint8{0, 19, 37, 61}

func (i RefreshTokenReqType) String() string {
	if i < 0 || i >= RefreshTokenReqType(len(_RefreshTokenReqType_index)-1) {
		return "RefreshTokenReqType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _RefreshTokenReqType_name[_RefreshTokenReqType_index[i]:_RefreshTokenReqType_index[i+1]]
}
