// Code generated by "stringer -type=wsEndpointType"; DO NOT EDIT.

package defs

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[wsEndpointTypeUsernamePassword-0]
	_ = x[wsEndpointTypeWindowsTransport-1]
}

const _wsEndpointType_name = "wsEndpointTypeUsernamePasswordwsEndpointTypeWindowsTransport"

var _wsEndpointType_index = [...]uint8{0, 30, 60}

func (i wsEndpointType) String() string {
	if i < 0 || i >= wsEndpointType(len(_wsEndpointType_index)-1) {
		return "wsEndpointType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _wsEndpointType_name[_wsEndpointType_index[i]:_wsEndpointType_index[i+1]]
}
