// Code generated by "stringer -type=UserRealmAccountType"; DO NOT EDIT.

package msalbase

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Federated-1]
	_ = x[Managed-2]
}

const _UserRealmAccountType_name = "UnknownFederatedManaged"

var _UserRealmAccountType_index = [...]uint8{0, 7, 16, 23}

func (i UserRealmAccountType) String() string {
	if i < 0 || i >= UserRealmAccountType(len(_UserRealmAccountType_index)-1) {
		return "UserRealmAccountType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserRealmAccountType_name[_UserRealmAccountType_index[i]:_UserRealmAccountType_index[i+1]]
}
